### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#141]
```
panic: send on closed channel

goroutine 15413 [running]:
github.com/pion/ion-sfu/pkg.(*WebRTCSender).receiveRTCP(0xc002572e40)
	/go/src/github.com/pion/ion-sfu/pkg/sender.go:151 +0x18a
created by github.com/pion/ion-sfu/pkg.NewWebRTCSender
	/go/src/github.com/pion/ion-sfu/pkg/sender.go:65 +0x1c8
```

**Comment by OrlandoCo** [comment]
I think that is necessary to check for ctx.done in *WebRTCSender.receiveRTCP because the sender can be closed by closing the router and close the channels, but meanwhile the negotiation is done the sender can still recieve packages from sub.

```go
func (s *WebRTCSender) receiveRTCP() {
	for {
		pkts, err := s.sender.ReadRTCP()
                // check for ctx done ************************************
		if err == io.ErrClosedPipe || err == io.EOF || s.ctx.Err() != nil {
			return
		}

		if err != nil {
			log.Errorf("rtcp err => %v", err)
		}

		for _, pkt := range pkts {
			switch pkt := pkt.(type) {
			case *rtcp.PictureLossIndication, *rtcp.FullIntraRequest, *rtcp.TransportLayerNack:
				s.rtcpCh <- pkt
			case *rtcp.ReceiverEstimatedMaximumBitrate:
				if s.useRemb {
					s.rembCh <- pkt
				}
			}
		}
	}
}
```

**Comment by tarrencev** [comment]
yup i think that is exactly correct. we do it in other methods. would you like to contribute a fix? :)
