### ISSUE TITLE
incorrect comparison can cause index OOR

### ISSUE THREAD

**Issue by tmiv** [pion/ion-sfu#350]
The comparison here 
https://github.com/pion/ion-sfu/blob/6c36fd4b7486ee153d6931efd0ebfdce21c2564f/pkg/buffer/nack.go#L50
is incorrect and can cause a short circuit failure and OOR error.

```
2020-12-29 17:36:19.996] [DEBUG] [64][subscriber.go][func1] => ice connection state: connected
[2020-12-29 17:36:25.905] [DEBUG] [64][publisher.go][func3] => ice connection state: disconnected
panic: runtime error: index out of range [0] with length 0

goroutine 227 [running]:
github.com/pion/ion-sfu/pkg/buffer.(*nackQueue).remove(0xc00066d800, 0xc0005a7b5a)
        /srv/ion-sfu/pkg/buffer/nack.go:50 +0x179
github.com/pion/ion-sfu/pkg/buffer.(*Bucket).addPacket(0xc0002966c0, 0xc000b3e000, 0x3de, 0x2000, 0x7b5a, 0x51679f, 0xa, 0xc0002691e0)
        /srv/ion-sfu/pkg/buffer/bucket.go:37 +0x2d9
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc000264a50, 0xc000b3e000, 0x3de, 0x2000, 0x16554086103e92af)
        /srv/ion-sfu/pkg/buffer/buffer.go:250 +0x105
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Write(0xc000264a50, 0xc000b3e000, 0x3de, 0x2000, 0x0, 0x0, 0x0)
        /srv/ion-sfu/pkg/buffer/buffer.go:184 +0x11d
github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc000645cc0, 0xc000b3e000, 0x3de, 0x2000, 0xc000b3e000, 0x3e8, 0x2000)
        /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/stream_srtp.go:63 +0x56
github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc00035f4a0, 0xc000b3e000, 0x3e8, 0x2000, 0x3e8, 0x0)
        /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session_srtp.go:160 +0x1a8
github.com/pion/srtp/v2.(*session).start.func1(0xc00035f4a0, 0xc0001c99b0, 0xc66720, 0xc00035f4a0)
        /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session.go:141 +0x12d
created by github.com/pion/srtp/v2.(*session).start
        /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session.go:120 +0x226
```

**Comment by OrlandoCo** [comment]
@tmiv this a strange case because an out of order packet arrived but the nack was not present in the list, so it was with a length of 0, the comparission is not valid since `i>=leng(nack)`  `i` can be the same length of slice, let me check with more detail why this could happen
