### ISSUE TITLE
SFU has killed when trying to switch video to screen share

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#428]
### Your environment.
  - Version: *Git*
  - Client: *include version*
  - Environement: *Windows*
  - Are you using a TURN server? *coturn?*
  - Other Information - *43c-d502-429d-9418-19d60cc403c3 mediaSSRC: 3824979377 rid :f streamID: 31e533c7-6db7-4f1b-88bf-030c49c18126
[2021-02-17 13:02:13.456] [DEBUG] [178][router.go][AddReceiver] => Setting feedback goog-remb
[2021-02-17 13:02:13.458] [DEBUG] [178][router.go][AddReceiver] => Setting feedback transport-cc
[2021-02-17 13:02:13.461] [DEBUG] [178][router.go][AddReceiver] => Setting feedback nack
[2021-02-17 13:02:13.463] [DEBUG] [178][router.go][AddReceiver] => Setting feedback nack
[2021-02-17 13:02:13.463] [DEBUG] [178][router.go][AddReceiver] => NewBuffer BufferOptions={1000 1500}
[2021-02-17 13:02:13.465] [INFO] [50][publisher.go][func1] => Publishing track to peer ckl9129nk000178326iirjq7n
[2021-02-17 13:02:13.467] [INFO] [50][publisher.go][func1] => Publishing track to peer ckl9129nk000278327trp7zyh
[2021-02-17 13:02:13.718] [DEBUG] [101][peer.go][func1] => peer ckl9129nk000178326iirjq7n negotiation needed
[2021-02-17 13:02:13.719] [DEBUG] [101][peer.go][func1] => peer ckl9129nk000278327trp7zyh negotiation needed
[2021-02-17 13:02:13.719] [INFO] [110][peer.go][func1] => peer ckl9129nk000178326iirjq7n send offer
[2021-02-17 13:02:13.726] [INFO] [110][peer.go][func1] => peer ckl9129nk000278327trp7zyh send offer
[2021-02-17 13:02:13.961] [INFO] [184][peer.go][SetRemoteDescription] => peer ckl9129nk000278327trp7zyh got answer
[2021-02-17 13:02:13.990] [INFO] [184][peer.go][SetRemoteDescription] => peer ckl9129nk000178326iirjq7n got answer
[2021-02-17 13:02:53.387] [WARN] [395][downtrack.go][writeSimulcastRTP] => old packet received, can not be sequenced, head: 14225 received: 17880
panic: runtime error: index out of range [14] with length 0

goroutine 548 [running]:
github.com/pion/ion-sfu/pkg/sfu.packetMeta.setVP8PayloadMeta(...)
        C:/ion-sfu-master/pkg/sfu/sequencer.go:61
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).writeSimulcastRTP(0xc00175c000, 0x0, 0x166473b1a902959c, 0x10002, 0x14, 0x69a06fad37910060, 0x8827ecdf, 0x1184dc8, 0x0, 0x0, ...)
        C:/ion-sfu-master/pkg/sfu/downtrack.go:397 +0xa29
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).WriteRTP(0xc00175c000, 0x0, 0x166473b1a902959c, 0x10002, 0x14, 0x69a06fad37910060, 0x8827ecdf, 0x1184dc8, 0x0, 0x0, ...)
        C:/ion-sfu-master/pkg/sfu/downtrack.go:151 +0x98
github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).writeRTP(0xc0000724e0, 0x1)
        C:/ion-sfu-master/pkg/sfu/receiver.go:273 +0x198
created by github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).AddUpTrack
        C:/ion-sfu-master/pkg/sfu/receiver.go:114 +0x146*

### What did you do?
I switch video track for the current stream
```
    var prevTrack = this.currentStream.getVideoTracks()[0];
    prevTrack.stop();
    this.currentStream.removeTrack(prevTrack);
    const newTrack = stream.getVideoTracks()[0];
    this.currentStream.addTrack(newTrack);
    this.currentVideoTrack = newTrack;
    this.currentClientObject.publish(this.currentStream);
```

### What did you expect?
I expect all participant able to see my screen sharing. I'm using simulcast btw. Am I doing it wrong?

### What happened?
Error and the sfu is autokill

**Comment by OrlandoCo** [comment]
@edwinsyarief this seems to be a racing issue during layer change, going to fix it this weekend, thxs for the reports!! this is related to your other issue.

**Comment by edwinsyarief** [comment]
Fixed with the latest version
