### ISSUE TITLE
Panic stemming from sendStreamDownTracksReports

### ISSUE THREAD

**Issue by tab1293** [pion/ion-sfu#433]
### Your environment.
  - Version: **v1.9.0**
  - Client: **ion-sdk-js: 1.6.0**
  - Environement: **K8S**
  -  Are you using a TURN server?  **coturn**
  - Other Information
  ```
[2021-02-20 02:59:48.053] [INFO] [259][room.go][handlePeerAnswer] => peer ckld4vzg000000123b1x6l715 got answer
panic: runtime error: index out of range [3] with length 0

goroutine 434 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/local/go/src/encoding/binary/binary.go:112
github.com/pion/srtp/v2.(*Context).encryptRTCP(0xc00048eed0, 0x0, 0x0, 0x0, 0xc00033e158, 0x4, 0x8, 0xc0004f80b0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/srtcp.go:54 +0x373
github.com/pion/srtp/v2.(*Context).EncryptRTCP(0xc00048eed0, 0x0, 0x0, 0x0, 0xc00033e158, 0x4, 0x8, 0x0, 0xc000468d80, 0x439d18, ...)
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/srtcp.go:76 +0x14a
github.com/pion/srtp/v2.(*SessionSRTCP).write(0xc0004f80b0, 0xc00033e158, 0x4, 0x8, 0x4, 0x8, 0x0)
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session_srtcp.go:118 +0x105
github.com/pion/srtp/v2.(*WriteStreamSRTCP).Write(...)
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtcp.go:145
github.com/pion/webrtc/v3.(*PeerConnection).writeRTCP(0xc000217500, 0xc00012df90, 0x1, 0x1, 0xc0003f41e0, 0x6af900, 0xc000100000, 0x0)
	/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.4/peerconnection.go:1812 +0x17a
github.com/pion/interceptor.RTCPWriterFunc.Write(0xc00037edd0, 0xc00012df90, 0x1, 0x1, 0xc0003f41e0, 0xc0003e1620, 0xc00030a340, 0x0)
	/go/pkg/mod/github.com/pion/interceptor@v0.0.9/interceptor.go:92 +0x63
github.com/pion/webrtc/v3.(*PeerConnection).WriteRTCP(...)
	/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.4/peerconnection.go:1792
github.com/pion/ion-sfu/pkg/sfu.(*Subscriber).sendStreamDownTracksReports.func1(0xc00012df90, 0x1, 0x1, 0xc0003c6100)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/subscriber.go:273 +0xfe
created by github.com/pion/ion-sfu/pkg/sfu.(*Subscriber).sendStreamDownTracksReports
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/subscriber.go:269 +0x3ac
```

### What did you do?
Connected two peers to the sfu, the server crashed on the second peer join
### What did you expect?
No crash
### What happened?
ion-sfu crashed with the above panic

**Comment by OrlandoCo** [comment]
Interesting, this seems to be a Pion internal error, have never seen it before, going to take a look on it

**Comment by OrlandoCo** [comment]
@tab1293 Closing now is fixed on master
