### ISSUE TITLE
Consistent panic on publisher join

### ISSUE THREAD

**Issue by tab1293** [pion/ion-sfu#450]
### Your environment.
  - Version: v1.9.1
  - Client: v1.6.0
  - Environment: K8S
  - Are you using a TURN server? Coturn
  - Other Information
  ```
[2021-03-01 22:37:09.657] [DEBUG] [128][peer.go][func3] => on publisher ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.692] [DEBUG] [128][peer.go][func3] => on publisher ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.692] [DEBUG] [128][peer.go][func3] => on publisher ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.693] [DEBUG] [128][peer.go][func3] => on publisher ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.695] [DEBUG] [128][peer.go][func3] => on publisher ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.894] [DEBUG] [63][publisher.go][func3] => ice connection state: connected
[2021-03-01 22:37:09.902] [DEBUG] [101][peer.go][func1] => peer 960f7958-25bc-47f6-b0c7-85eb30c85a50 negotiation needed
[2021-03-01 22:37:09.904] [INFO] [110][peer.go][func1] => peer 960f7958-25bc-47f6-b0c7-85eb30c85a50 send offer
[2021-03-01 22:37:09.905] [DEBUG] [116][peer.go][func2] => on subscriber ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.915] [DEBUG] [116][peer.go][func2] => on subscriber ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.916] [DEBUG] [116][peer.go][func2] => on subscriber ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.917] [DEBUG] [116][peer.go][func2] => on subscriber ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:09.918] [DEBUG] [116][peer.go][func2] => on subscriber ice candidate called for peer 960f7958-25bc-47f6-b0c7-85eb30c85a50
[2021-03-01 22:37:10.002] [DEBUG] [57][subscriber.go][func1] => ice connection state: checking
[2021-03-01 22:37:10.155] [DEBUG] [48][publisher.go][func1] => Peer 960f7958-25bc-47f6-b0c7-85eb30c85a50 got remote track id: 2c559dd0-cfbb-4ebd-a255-88e46b1c3448 mediaSSRC: 2736473610 rid : streamID: f98e5a49-3179-45d2-89f9-0283ad829132
[2021-03-01 22:37:10.155] [DEBUG] [180][router.go][AddReceiver] => Setting feedback goog-remb
[2021-03-01 22:37:10.155] [DEBUG] [180][router.go][AddReceiver] => Setting feedback transport-cc
[2021-03-01 22:37:10.156] [DEBUG] [180][router.go][AddReceiver] => Setting feedback nack
[2021-03-01 22:37:10.156] [DEBUG] [180][router.go][AddReceiver] => Setting feedback nack
panic: runtime error: index out of range [1] with length 0

goroutine 243 [running]:
encoding/binary.bigEndian.PutUint16(...)
	/usr/local/go/src/encoding/binary/binary.go:106
github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/buffer/bucket.go:59
github.com/pion/ion-sfu/pkg/buffer.(*Bucket).AddPacket(0xc000595c80, 0xc0005fb100, 0xf4, 0xf4, 0xc000016f73, 0x0, 0x10e7852, 0x17, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/buffer/bucket.go:37 +0x5b2
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc00045ed80, 0xc0005fb100, 0xf4, 0xf4, 0x166858ea65114ef7)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/buffer/buffer.go:304 +0x4e7
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Bind(0xc00045ed80, 0xc00058f2c0, 0x3, 0x4, 0xc00051a1e0, 0x1, 0x1, 0x1f40)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/buffer/buffer.go:169 +0x5a5
github.com/pion/ion-sfu/pkg/sfu.(*router).AddReceiver(0xc000138640, 0xc00051a360, 0xc0000b2c60, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/sfu/router.go:180 +0x7d5
github.com/pion/ion-sfu/pkg/sfu.NewPublisher.func1(0xc0000b2c60, 0xc00051a360)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.1/pkg/sfu/publisher.go:49 +0x2a5
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
	/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.10/peerconnection.go:451 +0x165
```

### What did you do?
Publisher joined a session

### What did you expect?
Publisher's tracks to be forwarded correctly

### What happened?
ion-sfu panics consistently with the error above

**Comment by OrlandoCo** [comment]
@tab1293 There was an update in the config file, did you update it on your side?

**Comment by tab1293** [comment]
That fixed the issue, I was still using `maxbuffertime`. Maybe there could be a default value here (with a log warning) as to not create this issue for others coming from an old config?

**Comment by OrlandoCo** [comment]
@tab1293 you are right going to fix it!
