### ISSUE TITLE
Server crash when the 6th participant join the session

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#454]
### Your environment.
  - Version: latest from git (1.9.3)
  - Client: 1.6.2
  - Environement: Windows
  - Are you using a TURN server? coturn
  - Other Information - [2021-03-03 13:41:21.345] [DEBUG] [57][subscriber.go][func1] => ice connection state: connected
[2021-03-03 13:41:21.516] [DEBUG] [101][peer.go][func1] => peer Adam negotiation needed
[2021-03-03 13:41:21.517] [INFO] [110][peer.go][func1] => peer Adam send offer
[2021-03-03 13:41:21.522] [DEBUG] [101][peer.go][func1] => peer Alex negotiation needed
[2021-03-03 13:41:21.522] [INFO] [110][peer.go][func1] => peer Alex send offer
[2021-03-03 13:41:21.525] [DEBUG] [101][peer.go][func1] => peer Student 3 negotiation needed
[2021-03-03 13:41:21.525] [INFO] [110][peer.go][func1] => peer Student 3 send offer
[2021-03-03 13:41:21.527] [DEBUG] [101][peer.go][func1] => peer Edwin negotiation needed
[2021-03-03 13:41:21.527] [DEBUG] [101][peer.go][func1] => peer Hay Min negotiation needed
[2021-03-03 13:41:21.527] [INFO] [110][peer.go][func1] => peer Edwin send offer
[2021-03-03 13:41:21.528] [INFO] [110][peer.go][func1] => peer Hay Min send offer
[2021-03-03 13:41:21.969] [INFO] [184][peer.go][SetRemoteDescription] => peer Adam got answer
[2021-03-03 13:41:22.036] [INFO] [184][peer.go][SetRemoteDescription] => peer Alex got answer
[2021-03-03 13:41:22.036] [INFO] [184][peer.go][SetRemoteDescription] => peer Student 3 got answer
[2021-03-03 13:41:22.038] [INFO] [184][peer.go][SetRemoteDescription] => peer Hay Min got answer
[2021-03-03 13:41:22.038] [INFO] [184][peer.go][SetRemoteDescription] => peer Edwin got answer
panic: runtime error: index out of range [3] with length 0

goroutine 3244 [running]:
encoding/binary.bigEndian.Uint32(...)
        c:/go/src/encoding/binary/binary.go:112
github.com/pion/srtp/v2.(*Context).encryptRTCP(0xc00006a8d0, 0x0, 0x0, 0x0, 0xc00166e198, 0x4, 0x8, 0xc0005f7da8, 0x13674b, 0xc00097efc0, ...)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/srtcp.go:54 +0x16e
github.com/pion/srtp/v2.(*Context).EncryptRTCP(0xc00006a8d0, 0x0, 0x0, 0x0, 0xc00166e198, 0x4, 0x8, 0x0, 0x0, 0x8, ...)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/srtcp.go:76 +0x105
github.com/pion/srtp/v2.(*SessionSRTCP).write(0xc000bb96b0, 0xc00166e198, 0x4, 0x8, 0x4, 0x8, 0x0)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session_srtcp.go:118 +0xcb
github.com/pion/srtp/v2.(*WriteStreamSRTCP).Write(...)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtcp.go:145
github.com/pion/webrtc/v3.(*PeerConnection).writeRTCP(0xc000174fc0, 0xc00105a020, 0x1, 0x1, 0xc000182750, 0xc001a42240, 0xc0019d62e0, 0xc0005f7f20)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.10/peerconnection.go:1828 +0xf3
github.com/pion/interceptor.RTCPWriterFunc.Write(0xc000264cc0, 0xc00105a020, 0x1, 0x1, 0xc000182750, 0x0, 0x0, 0x17513d)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/interceptor@v0.0.9/interceptor.go:92 +0x55
github.com/pion/webrtc/v3.(*PeerConnection).WriteRTCP(...)
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.10/peerconnection.go:1808
github.com/pion/ion-sfu/pkg/sfu.(*Subscriber).sendStreamDownTracksReports.func1(0xc00105a020, 0x1, 0x1, 0xc00018c380)
        C:/sfu/sfu-server/pkg/sfu/subscriber.go:278 +0xa3
created by github.com/pion/ion-sfu/pkg/sfu.(*Subscriber).sendStreamDownTracksReports
        C:/sfu/sfu-server/pkg/sfu/subscriber.go:274 +0x2cb

### What did you do?
Trying to push the limit to see how many participant can handle (all participants using desktop). But the 6th participant (using mobile chrome) joining in, the server crash immediately

### What did you expect?
Server should handle more than 30 participants

### What happened?
Server crashed

**Comment by OrlandoCo** [comment]
with 30 users you mean 30vs30 in single conference room? 

This error seems to be on Pion internals but need to check why is fired.

**Comment by edwinsyarief** [comment]
What do you mean by 30vs30? I don't get it. Because, it is still 6 participants in the room but the server is crashed already

**Comment by edwinsyarief** [comment]
@OrlandoCo , can you help me to fix this issue? Because, it is random, sometimes not sometimes yes. Between 5 or above participants will always crash. And I need this system run today.

Thanks in advance

**Comment by adwpc** [comment]
seems only happen when using coturn?

**Comment by OrlandoCo** [comment]
@edwinsyarief please test with master, it should be fixed now. Can you tell me if your clients are browsers or other Pion instances?

**Comment by edwinsyarief** [comment]
> @edwinsyarief please test with master, it should be fixed now. Can you tell me if your clients are browsers or other Pion instances?

Okay, I will try again. Clients are using desktop browser and mobile browser.

Thank you.

**Comment by edwinsyarief** [comment]
> @edwinsyarief please test with master, it should be fixed now. Can you tell me if your clients are browsers or other Pion instances?

Hi @OrlandoCo ,

Do you have any suggestion how to reduce high cpu usage on desktop browser also mobile browser? Very lag when 5 participant above.

Thank you.

Best Regards,
edwin

**Comment by edwinsyarief** [comment]
Is there any configuration to lower bitrate?

**Comment by OrlandoCo** [comment]
@edwinsyarief you can set lower bitrate in the client side thourgh javascript api, you can also lower the FPS. For CPU usage, are you using VP8?? vp8 is softwared decoded so it can be pretty expesive, you should try with h264 and maybe limit fps

**Comment by edwinsyarief** [comment]
> @edwinsyarief you can set lower bitrate in the client side thourgh javascript api, you can also lower the FPS. For CPU usage, are you using VP8?? vp8 is softwared decoded so it can be pretty expesive, you should try with h264 and maybe limit fps

How to do that in javascript API, because there is no doc about it. I think the current sfu simulcast still vp8 only? because I don't know how to implement with h264. Please provide some example?

Thank you.

Best Regards

**Comment by edwinsyarief** [comment]
Hi @OrlandoCo ,

I'm able to implement the bitrate optimization on the client side. But, there is still some issue when the participant above 5.

I still see these a lot on the server log:

```
[2021-03-16 11:08:38.034] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m11764 [36mreceived=[0m10172 [36mv=[0m0
[2021-03-16 11:08:38.036] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m11764 [36mreceived=[0m11041 [36mv=[0m0
turnc ERROR: 2021/03/16 11:08:40 fail to refresh permissions: CreatePermission error response (error 437: Allocation Not Found)
[2021-03-16 11:09:03.346] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m12476 [36mreceived=[0m10664 [36mv=[0m0
[2021-03-16 11:09:03.347] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m12476 [36mreceived=[0m10664 [36mv=[0m0
```

And because of this issue, all the participants video become black or freeze

Thank you.

Best Regards,
Edwin

**Comment by edwinsyarief** [comment]
> Hi @OrlandoCo ,
> 
> 
> 
> I'm able to implement the bitrate optimization on the client side. But, there is still some issue when the participant above 5.
> 
> 
> 
> I still see these a lot on the server log:
> 
> 
> 
> ```
> 
> [2021-03-16 11:08:38.034] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m11764 [36mreceived=[0m10172 [36mv=[0m0
> 
> [2021-03-16 11:08:38.036] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m11764 [36mreceived=[0m11041 [36mv=[0m0
> 
> turnc ERROR: 2021/03/16 11:08:40 fail to refresh permissions: CreatePermission error response (error 437: Allocation Not Found)
> 
> [2021-03-16 11:09:03.346] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m12476 [36mreceived=[0m10664 [36mv=[0m0
> 
> [2021-03-16 11:09:03.347] [INFO] [sequencer.go:87] => Old packet received, can not be sequenced [36mhead=[0m12476 [36mreceived=[0m10664 [36mv=[0m0
> 
> ```
> 
> 
> 
> And because of this issue, all the participants video become black or freeze
> 
> 
> 
> Thank you.
> 
> 
> 
> Best Regards,
> 
> Edwin

@OrlandoCo , maybe you also can help me to provide an example how to use h264 on client side please?

Thank you.

**Comment by OrlandoCo** [comment]
@edwinsyarief seems that your peers are getting really congested, did you check if the CPU is your contraint and not the network?

**Comment by edwinsyarief** [comment]
@OrlandoCo,

Yes, I have checked the CPU usage for all participants, and there is no problem, even on participants which experience a very little lag, but they can see all other participants video in the real time. But there is a single participant which have 10Mbps internet speed. Do you think it is related to that issue?

I only use vp8, for the current implementation, because there is no example for h264. I hope there will be a good example which can improve performance and keep connection of all participant stable.

I'm currently implementing from link below:
https://stackoverflow.com/questions/16712224/how-to-control-bandwidth-in-webrtc-video-call

Do you think there is a better approach?

Thank you

**Comment by edwinsyarief** [comment]
Sorry, there is some error when I'm trying to modify offer.sdp or answer.sdp

error creating answer: TypeError: provided value is not a valid enum value of type SDPType: '0' is not a valid enum value of type SDPType

previously I've said working because the function to update sdp not called.

Best Regards,
Edwin

**Comment by edwinsyarief** [comment]
Hi @OrlandoCo ,

When I have only two participants, when I'm sharing screen, why still get this error?

[2021-03-18 13:37:27.716] [INFO] [peer.go:110] => Send offer [36mpeer_id=[0mAdam [36mv=[0m0
[2021-03-18 13:37:27.719] [INFO] [peer.go:110] => Send offer [36mpeer_id=[0m"LiYin 2" [36mv=[0m0
[2021-03-18 13:37:28.068] [INFO] [peer.go:184] => Peer got answer [36mpeer_id=[0m"LiYin 2" [36mv=[0m0
[2021-03-18 13:37:28.069] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.069] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.069] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.091] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.092] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.094] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.111] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m
[2021-03-18 13:37:28.115] [ERROR] [subscriber.go:281] => Sending track binding reports err [31merror=[0m[31m"rtcp: too many chunks"[0m

When there is another user which just joined the session will only see black screen

Thank you

**Comment by adwpc** [comment]
pls try new version
