### ISSUE TITLE
 panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by tmiv** [pion/ion-sfu#464]
### Your environment.
  - Version: v1.9.4 - v1.9.1 ( last working version v1.9.0 )
  - Client: Chrome -- Version 88.0.4324.190 (Official Build) (64-bit)
  - Environement: GCP
  - Are you using a TURN server? No

### What did you do?
Connect to sfu causes crash.

### What happened?
```
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: panic: runtime error: index out of range [1] with length 0
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: goroutine 195 [running]:
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: encoding/binary.bigEndian.PutUint16(...)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /usr/local/go/src/encoding/binary/binary.go:106
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/buffer/bucket.go:59
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).AddPacket(0xc000274ff0, 0xc00000ad00, 0xf4, 0xf4, 0x104cb, 0x2, 0x203000, 0x203000, 0
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/buffer/bucket.go:37 +0x26f
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc000200000, 0xc00000ad00, 0xf4, 0xf4, 0x166bfda7f4c9e7c8)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/buffer/buffer.go:313 +0x1e5
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Bind(0xc000200000, 0xc0000ba7e0, 0x3, 0x4, 0xc0000e0000, 0x7, 0x8, 0x5dc)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/buffer/buffer.go:178 +0x287
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/sfu.(*router).AddReceiver(0xc0001aba40, 0xc000466180, 0xc0000c4d80, 0x0, 0x0, 0x0)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/sfu/router.go:179 +0x47a
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: github.com/pion/ion-sfu/pkg/sfu.NewPublisher.func1(0xc0000c4d80, 0xc000466180)
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/ion-sfu/pkg/sfu/publisher.go:55 +0x354
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]: created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
Mar 13 19:29:49 tmiv-nakama-1 launch-sfu.sh[15959]:         /srv/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.10/peerconnection.go:451 +0x10f
Mar 13 19:29:49 tmiv-nakama-1 systemd[1]: ion-sfu.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 13 19:29:49 tmiv-nakama-1 systemd[1]: ion-sfu.service: Failed with result 'exit-code'.
Mar 13 19:29:50 tmiv-nakama-1 systemd[1]: ion-sfu.service: Service RestartSec=1s expired, scheduling restart.
```

**Comment by OrlandoCo** [comment]
@tmiv there was a change in the config file, need to update it.

Sorry for the inconvenience, going to  fix to not cause panics the next update

**Comment by tmiv** [comment]
Oh. I see. Thank you. That fixed it.
