### ISSUE TITLE
Panicked when running on ARM32 arch

### ISSUE THREAD

**Issue by junekimdev** [pion/ion-sfu#577]
### Your environment.
  - Version: *1.10.8*
  - Client: *ion-sdk-js@1.5.5*
  - Environement: *Docker on ARM32v7 system*
  - Are you using a TURN server? *coturn*
  - Other Information
      - *stacktraces*
        ```
        [2021-08-26 05:22:38.510] [INFO] [logr.go:208] => Config file loaded file=/configs/sfu.toml v=0
        [2021-08-26 05:22:38.511] [INFO] [logr.go:208] => --- Starting SFU Node --- v=0
        [2021-08-26 05:22:38.512] [INFO] [logr.go:208] => Started listening addr=http://:7000 v=0
        [2021-08-26 05:22:38.513] [INFO] [logr.go:208] => Metrics Listening addr=:8100 v=0
        [2021-08-26 05:23:59.704] [INFO] [logr.go:208] => PeerLocal join SessionLocal peer_id=cksshdtw80000ns33awkurmrs session_id="test session" v=0
        [2021-08-26 05:23:59.705] [INFO] [logr.go:208] => PeerLocal got offer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.744] [INFO] [logr.go:208] => PeerLocal send answer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.748] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.752] [INFO] [logr.go:208] => PeerLocal join SessionLocal peer_id=cksshdtw80001ns33wunzqsoz session_id="test session" v=0
        [2021-08-26 05:23:59.752] [INFO] [logr.go:208] => PeerLocal got offer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:23:59.759] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.770] [INFO] [logr.go:208] => PeerLocal send answer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:23:59.773] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:23:59.774] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:23:59.974] [INFO] [logr.go:208] => Send offer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.990] [INFO] [logr.go:208] => PeerLocal got answer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:23:59.991] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:00.017] [INFO] [logr.go:208] => Send offer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:00.030] [INFO] [logr.go:208] => PeerLocal got answer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:00.033] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:00.034] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:00.076] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:04.753] [INFO] [logr.go:208] => Send offer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:04.774] [INFO] [logr.go:208] => PeerLocal got answer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:11.991] [INFO] [logr.go:208] => PeerLocal got offer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:11.997] [INFO] [logr.go:208] => PeerLocal send answer peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:12.033] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:12.047] [INFO] [logr.go:208] => PeerLocal trickle peer_id=cksshdtw80000ns33awkurmrs v=0
        [2021-08-26 05:24:12.098] [INFO] [logr.go:208] => Publishing track to peer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:12.224] [INFO] [logr.go:208] => Publishing track to peer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:12.478] [INFO] [logr.go:208] => Send offer peer_id=cksshdtw80001ns33wunzqsoz v=0
        [2021-08-26 05:24:12.674] [INFO] [logr.go:208] => PeerLocal got answer peer_id=cksshdtw80001ns33wunzqsoz v=0
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e38]
        
        goroutine 374 [running]:
        runtime/internal/atomic.goLoad64(0x16225dc, 0xc041e73f, 0xf0020bcf)
                /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
        github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).SendRTCP(0x16225a0, 0x1572f18, 0x1, 0x1)
                /go/src/github.com/pion/ion-sfu/pkg/sfu/receiver.go:265 +0xbc
        github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).writeSimpleRTP(0x15db200, 0x1627680, 0x1622658, 0x160f230)
                /go/src/github.com/pion/ion-sfu/pkg/sfu/downtrack.go:347 +0x2a4
        github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).WriteRTP(0x15db200, 0x1627680, 0x0, 0x0, 0x0)
                /go/src/github.com/pion/ion-sfu/pkg/sfu/downtrack.go:161 +0xa4
        github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).writeRTP(0x16225a0, 0x0)
                /go/src/github.com/pion/ion-sfu/pkg/sfu/receiver.go:371 +0x134
        created by github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).AddUpTrack
                /go/src/github.com/pion/ion-sfu/pkg/sfu/receiver.go:164 +0x224
        ```
      - *suggestions how to fix*
        1. Refactor all 64 bit specific codes (e.g. `atomic.LoadInt64`)
        1. Tell developers NOT TO BUILD on 32 bit architecture
      - *links for us to have context* : https://pkg.go.dev/sync/atomic#pkg-note-BUG

### What did you do?

1. Built a docker image with `/cmd/signal/json-rpc/Dockerfile` on my Single Board Computer with ARM32v7 arch CPU
2. Modified config.toml to add my `coturn` server info
3. Run a file `/examples/echotest/index.html` on my laptop
4. Hit `Start` button

### What did you expect?
1. Run successfully

### What happened?
1. Got panic
2. The container restarted by Docker

**Comment by adwpc** [comment]
It's hard because pion use many int64 uint64

**Comment by junekimdev** [comment]
> 

Yep, that's what I thought.
So, I guess Option B is better, which is "Tell developers NOT TO BUILD on 32 bit architecture" explicitly.

**Comment by adwpc** [comment]
@junekimdev thanks
